name: BentoBox-FarmersDance
main: world.bentobox.farmersdance.FarmersDancePladdon
version: ${project.version}${build.number}
api-version: "1.19"

authors: [BONNe]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: ${project.description}
